# config/services.yaml
parameters: 

services:
  _defaults:
    autowire: true
    autoconfigure: true

  # 1) Primero, registra todo src/ de forma genérica
  App\:
    resource: '../src/'
    exclude:
      - '../src/Entity/'
      - '../src/Kernel.php'

  # 2) Después, sobrescribe SOLO los scrapers y añade la tag
  App\Scraper\ElPaisScraper:
    tags: ['app.scraper']

  App\Scraper\ElMundoScraper:
    tags: ['app.scraper']

